language: node_js
sudo: true
dist: trusty

node_js:
- '6.9.4'

install:
- npm install
- npm install -g codecov typescript istanbul

script:
  - tsc -p tsconfig-mocha.json
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec test/**/*.spec.js
  - codecov