let TYPES = {
    Kernel: Symbol("Kernel"),
    Process: Symbol("Process"),
    SettingsProvider: Symbol("SettingsProvider"),
    PackageJson: Symbol("package.json"),
    Commands: Symbol("Commands"),
    CommandFactory: Symbol("CommmandFactory"),
    Path: Symbol("Path"),
    FS: Symbol("FileSystem"),
    Glob: Symbol("Glob"),
    UserMessager: Symbol("UserMessager"),
    TemplateManager: Symbol("TemplateManager"),
    TemplateRunner: Symbol("TemplateRunner"),
    FilePatterns: Symbol("FilePatterns"),
    TransformManager: Symbol("TransformManager"),
    PathTransformManager: Symbol("PathTransformManager"),
    TemplateValidator: Symbol("TemplateValidator"),
    InputManager: Symbol("InputManager"),
    BrowserInputManager: Symbol("BrowserInputManager"),
    CustomInputManager: Symbol("CustomInputManager"),
    PromptInputManager: Symbol("PromptInputManager"),
    DefaultsInputManager: Symbol("DefaultsInputManager"),
    HandlerService: Symbol("HandlerService"),
    i18n: Symbol("i18n"),
    Mapper: Symbol("Mapper"),
    SettingsType: Symbol("SettingsType"),
    ErrorReporter: Symbol("ErrorReporter"),
    TemplateInfo: Symbol("TemplateInfo")
}

export default TYPES;