import { IDefaultsAnswerer } from "./i-defaults-answerer";
import { injectable } from "inversify";
import { ITemplateTypedInput, ITemplateScriptedInput } from "../../user-extensibility";

@injectable()
export class DefaultsAnswerer implements IDefaultsAnswerer {
    protected autoInc: number = 1;

    getDefault(def: string | ITemplateTypedInput | ITemplateScriptedInput): any {
        if ((<ITemplateTypedInput>def).default)
        {
            return (<ITemplateTypedInput>def).default;
        }

        return `NeomanAutogeneratedValue${(this.autoInc++).toFixed(3)}`;
    }
}